### ISSUE TITLE
まだコードが上がっていないです

### ISSUE THREAD

**Issue by tsunpoko** [Yoshifumi12321/gitpractice#1]
ちゃんとみていますよ

**Comment by Yoshifumi12321** [comment]
## about this repository
このリポジトリは後輩にGitについて教えるために用意したものとなっております。
気になるようでしたら未完成ですがPDFを載せておきます。[こちら](https://www.dropbox.com/s/ve3v2vsvr79e569/git%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6.pdf?dl=0)をご確認ください。

### gitについて
#### 目次
1. GitHubアカウントとリポジトリの作成
2. SourceTreeの設定
 2.1 SourceTreeのインストール
 2.2 GitHubのアカウント連携
 2.3 リポジトリのクローン
 2.4 Proxy設定
3. Gitの操作方法について
 3.1 コミット/プッシュ
 3.2 ブランチ/チェックアウト

**Comment by tsunpoko** [comment]
![LGTM](https://cdn.lgtmoon.dev/images/104709)
